apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptominer-app-demo
  labels:
    app: cryptominer-app
spec:
  selector:
    matchLabels:
        app: cryptominer-app
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cryptominer-app
    spec:
      containers:
        - name: cryptominer-app
          image: demo-image-name
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
